### ISSUE TITLE
What happens when someone put a minus value for the quantity ??  

### ISSUE THREAD

**Issue by gobzateloon** [indunilLakshitha/cart_demo#11]
https://github.com/indunilLakshitha/cart_demo/blob/31ec21b17bffa5307d3e5e3140efa2e38f75b0ca/Modules/CartItem/Http/Controllers/CartItemController.php#L19-L59

**Comment by indunilLakshitha** [comment]
`if($item_details['available_qty']==0 || $item_details['available_qty']< 0 || $item_details['status']=='blocked')`
