### ISSUE TITLE
Requests status code 201 ?? what does that mean ??

### ISSUE THREAD

**Issue by gobzateloon** [indunilLakshitha/cart_demo#4]
https://github.com/indunilLakshitha/cart_demo/blob/31ec21b17bffa5307d3e5e3140efa2e38f75b0ca/Modules/User/Http/Controllers/UserController.php#L14

**Comment by indunilLakshitha** [comment]
created

[](https://httpstatuses.com/201#:~:text=%C3%97%C3%97%20Success-,201%20Created,by%20the%20effective%20request%20URI.)
