### ISSUE TITLE
if you use foreign key for connect items, you don't need to keep item name and item price in the columns 

### ISSUE THREAD

**Issue by gobzateloon** [indunilLakshitha/cart_demo#6]
https://github.com/indunilLakshitha/cart_demo/blob/31ec21b17bffa5307d3e5e3140efa2e38f75b0ca/Modules/CartItem/Database/Migrations/2020_07_09_113434_create_cartitems_table.php#L20-L22

**Comment by indunilLakshitha** [comment]
updating
